#!/bin/sh
#
# Script name: bb_post_bedpostx_gpu
#
# Description: Script to join bedpostx output into usable data.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

subjdir=`fsl_abspath $1`
subjdir=`echo $subjdir | sed 's/\/$/$/g'`
meas=vol,prob,length,FA,MD,L1
if [ ! -d  ${subjdir}.xtract ]; then
    xtract -bpx ${subjdir}.bedpostX -out  ${subjdir}.xtract -species HUMAN \
    -stdwarp ${subjdir}/../TBSS/FA/MNI_to_dti_FA_warp.nii.gz \
    ${subjdir}/../TBSS/FA/dti_FA_to_MNI_warp.nii.gz -gpu \
    -ptx_options $BB_BIN_DIR/bb_data/ptx.txt
fi

# for para in ${meas};
# do
#     cp -R ${subjdir}.xtract ${subjdir}.${para}.xtract
    xtract_stats -d ${subjdir}/dti_ -xtract ${subjdir}.xtract \
    -w ${subjdir}/../TBSS/FA/MNI_to_dti_FA_warp.nii.gz \
    -meas $meas \
    -r ${subjdir}/dti_FA.nii.gz
# done

# xtract_viewer  -dir dMRI.xtract/ -species HUMAN -str slf1_r

. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer