#! /bin/sh
#
# Script name: bb_swi_reg
#
# Description: Script to run the swMRI processing
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
. $BB_BIN_DIR/bb_pipeline_tools/bb_set_header 

cd $1/SWI

T1dir="../T1/"

if [ -d $T1dir/unusable ] ; then
    T1dir="../T1/unusable/"
fi

# the SWI file is from the dcm2niix and JHU QSM tool box, 
# the nii.info of QSM.nii.gz should be replaced by the raw nii.info of GRE_echo_1.nii.gz
if [ `${FSLDIR}/bin/imtest QSM` = 0 ] ; then
  echo No QSM in $1
  exit
fi
if [ `${FSLDIR}/bin/imtest GRE_echo_1_orig` = 0 ] ; then
  ${FSLDIR}/bin/immv GRE_echo_1 GRE_echo_1_orig
fi



# ${FSLDIR}/bin/flirt -in GRE_echo_1_orig -ref $T1dir/T1 -dof 6 -omat SWI_to_T1.mat -o SWI_MAG_to_T1
# ${FSLDIR}/bin/convert_xfm -omat T1_to_SWI.mat -inverse SWI_to_T1.mat

# ${FSLDIR}/bin/convertwarp --ref=$FSLDIR/data/standard/MNI152_T1_1mm  \
#  --midmat=SWI_to_T1.mat --warp2=$T1dir/transforms/T1_to_MNI_warp --out=SWI_to_MNI_warp
${FSLDIR}/bin/applywarp --rel -i QSM_new -r $FSLDIR/data/standard/MNI152_T1_1mm \
  -w SWI_to_MNI_warp -o QSM_to_MNI --interp=spline

${FSLDIR}/bin/fslmaths QSM_to_MNI -mul $templ/MNI152_T1_1mm_brain_mask QSM_brain_to_MNI
$FSLDIR/bin/fslmaths QSM_brain_to_MNI -mul $T1dir/transforms/T1_to_MNI_warp_jac QSM_brain_to_MNI_mod -odt float


. $BB_BIN_DIR/bb_pipeline_tools/bb_set_footer 
