#!/usr/bin/env bash
#
# Script name: bb_tbss_general
#
# Description: General script to run the different phases of TBSS
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
# revised by Peng Sun
# should be called in the working directory, e.g. the subdir is subject dir
#

. "$BB_BIN_DIR"/bb_pipeline_tools/bb_set_header 

WorkDir=$1
meas=$2
TBSSDir="$WorkDir"/TBSS
# meas="DKI_MD DKI_FA DKI_AD DKI_RD DKI_MK DKI_AK DKI_RK DKI_MKT DKI_KFA ISOVF ICVF OD RTOP RTAP RTPP NORM MSD QIV NG NG_PER NG_PAR"
# meas="DKI_MK DKI_MKT DKI_KFA ISOVF RTOP MSD QIV NG"
# meas="DKI_MK"

cd $WorkDir
if [ ! -d $TBSSDir ] ; then
    mkdir "$TBSSDir"
fi

RawDir=$WorkDir/raw
sublist=($(ls $RawDir))
for sub in ${sublist[@]};  
do   
cp $RawDir/$sub/dMRI/dMRI/dti_FA.nii.gz "$TBSSDir"/hc_${sub}.nii.gz
done 

cd "$TBSSDir"
tbss_1_preproc *.nii.gz
tbss_2_reg -T
tbss_3_postreg -S
tbss_4_prestats 0.2

cd stats
design_ttest2 tbss 10 10
randomise -i all_FA_skeletonised -o tbss -m mean_FA_skeleton_mask -d tbss.mat \
-t tbss.con -n 100 --T2

# # show results
# fsleyes $FSLDIR/data/standard/MNI152_T1_1mm mean_FA_skeleton -cm Green -dr 0.2 0.7 \
# tbss_tfce_corrp_tstat1 -cm Red-Yellow -dr 0.7 1 \
# tbss_tfce_corrp_tstat2 -cm Blue-Lightblue -dr 0.7 1


# # thickens the threshold stats image
# tbss_fill tbss_tfce_corrp_tstat1 0.7 mean_FA tbss_fill95
# fsleyes mean_FA -dr 0 0.6 mean_FA_skeleton -cm Green -dr 0.2 0.7 \
# tbss_fill95 -cm  Red-Yellow

cd "$TBSSDir"
for para in ${meas}
do
    cd "$TBSSDir"
    if [ ! -d ${para} ] ; then
        mkdir "${para}"
        for sub in ${sublist[@]};  
        do   
            cp $RawDir/$sub/dMRI/dMRI/dti_${para}.nii.gz "$TBSSDir"/${para}/hc_${sub}.nii.gz
        done 
        tbss_non_FA ${para}
        cd stats
        randomise -i all_${para}_skeletonised -o ${para}_tbss -m mean_FA_skeleton \
        -d tbss.mat -t tbss.con -n 100 --T2
    fi
done
. "$BB_BIN_DIR"/bb_pipeline_tools/bb_set_footer 


# # show results
# fsleyes $FSLDIR/data/standard/MNI152_T1_1mm mean_FA_skeleton -cm Green -dr 0.2 0.7 \
# DKI_MK_tbss_tfce_corrp_tstat1 -cm Red-Yellow -dr 0.5 1 \
# DKI_MK_tbss_tfce_corrp_tstat2 -cm Blue-Lightblue -dr 0.5 1