#!/usr/bin/env bash
#
# Script name: bb_tbss_general
#
# Description: General script to run the different phases of TBSS
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
# revised by Peng Sun
# should be called in the working directory, e.g. the subdir is subject dir
#

. "$BB_BIN_DIR"/bb_pipeline_tools/bb_set_header 

direc="$PWD"
cd $direc
TBSSDir="$direc"/../TBSS
mkdir "$TBSSDir"

WorkingDir=$direc
sublist=($(ls $WorkingDir))

for sub in ${sublist[@]};  
do   
cp $direc/$sub/dMRI/dMRI/dti_FA.nii.gz "$TBSSDir"/${sub}_FA.nii.gz
done 

cd "$TBSSDir"
tbss_1_preproc *.nii.gz
tbss_2_reg -T
tbss_3_postreg -S
tbss_4_prestats 0.2

cd stats
design_ttest2 tbss 3 3
randomise -i all_FA_skeletonised -o FA_tbss -m mean_FA_skeleton_mask -d tbss.mat \
-t tbss.con -n 5000 --T2

# # show results
# fsleyes $FSLDIR/data/standard/MNI152_T1_1mm mean_FA_skeleton -cm Green -dr 0.2 0.7 \
# tbss_tfce_corrp_tstat1 -cm Red-Yellow -dr 0.8 1 \
# tbss_tfce_corrp_tstat2 -cm Blue-Lightblue -dr 0.8 1


# # thickens the threshold stats image
# tbss_fill tbss_tfce_corrp_tstat1 0.7 mean_FA tbss_fill95
# fsleyes mean_FA -dr 0 0.6 mean_FA_skeleton -cm Green -dr 0.2 0.7 \
# tbss_fill95 -cm  Red-Yellow

cd "$TBSSDir"

metrics="MD"
for para in ${metrics}
do
    mkdir ${para}
    WorkingDir=$direc
    sublist=($(ls $WorkingDir))

    for sub in ${sublist[@]};  
    do   
        cp $WorkingDir/$sub/dMRI/dMRI/dti_${para}.nii.gz "$TBSSDir"/${para}/${sub}_FA.nii.gz
    done 

    tbss_non_FA ${para}

    cd "$TBSSDir"
    design_ttest2 tbss 3 3
    cd stats
    randomise -i all_${para}_skeletonised -o ${para}_tbss -m mean_FA_skeleton_mask -d tbss.mat \
    -t tbss.con -n 5000 --T2

done

. "$BB_BIN_DIR"/bb_pipeline_tools/bb_set_footer 
